---
# create sudo group
- name: create sudo group
  group:
    name: wheel
    state: present

- name: Allow wheel group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

# Add system admin user
- name: create sudo user
  user:
    name: "{{ systemadmin }}"
    state: present
    groups: wheel
    append: true
    create_home: true
    shell: /bin/bash

- name: Set authorized key for remote user
  authorized_key:
    user: "{{ systemadmin }}"
    state: present
    key: "{{ copy_local_key }}"

- name: Disable root login
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    notify:
      - restart sshd

- name: Disable password login
    lineinfile: 
      dest: /etc/ssh/sshd_config 
      regexp: '^PasswordAuthentication' 
      line: 'PasswordAuthentication no' 
      state: present
    notify:
      - restart sshd

# Set server's hostname based on host variable
- name: set hostname
  hostname:
    name: "{{ server-hostname }}"