apiVersion: apps/v1
kind: Deployment
metadata:
  name: string-compression
  namespace: demo
  labels:
    app: string-compression
spec:
  selector:
    matchLabels:
      app: string-compression
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: string-compression
    spec:
      containers:
      - image: teehee/stringcompression:0.0.1
        imagePullPolicy: Always
        name: string-compression
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
        resources:
          requests:
            memory: 300Mi
            cpu: 300m
          limits:
            memory: 1Gi
            cpu: 1000m
        ports:
        - containerPort: 8080
        readinessProbe:
            httpGet:
                path: /
                port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
        livenessProbe:
            httpGet:
                path: /
                port: 8080
            initialDelaySeconds: 5
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: hpa-string-compression
    namespace: demo
spec:
    scaleTargetRef:
        apiVersion: extensions/v1beta1
        kind: Deployment
        name: string-compression
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
