apiVersion: v1
kind: Service
metadata:
  name: string-compression
  namespace: demo
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: string-compression

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: string-compression
    namespace: demo
    annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
    rules:
    - host: abc.xyz
    http:
        paths:
        - path: /(.*)
        backend:
            serviceName: string-compression
            servicePort: 80